### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Tippit** [YuAo/YUCIHighPassSkinSmoothing#1]
Very good job, thank you very much!

Could you tell me where to find  a skin detection filter ?

**Comment by YuAo** [comment]
You have to write it yourself. Google `skin detection`, there are lots of skin detection methods. Try to implement one.

**Comment by Tippit** [comment]
Thank's :)

Best,

On Sun, Jan 24, 2016 at 11:56 PM -0800, "Yu Ao" notifications@github.com wrote:

You have to write it yourself. Google skin detection, there are lots of skin detection methods. Try to implement one.
