### ISSUE TITLE
YUCIHighPassSkinSmoothing drains battery and increases CPU usage significantly 

### ISSUE THREAD

**Issue by vincent284** [YuAo/YUCIHighPassSkinSmoothing#10]
Hi Yu Ao,
Thanks for this sweet and useful library. 
I notice that after applying this filter for realtime processing (let's say from a camera running at 24fps), it drains battery very fast and incurs a lot more CPU usage. 
Could you please show some pointers on why this happens and how to mitigate it?
Thanks a lot.

**Comment by YuAo** [comment]
See [Getting the Best Performance - Core Image Programming Guide](https://developer.apple.com/library/content/documentation/GraphicsImaging/Conceptual/CoreImaging/ci_performance/ci_performance.html)
