### ISSUE TITLE
use too much cpu  

### ISSUE THREAD

**Issue by notedit** [YuAo/YUCIHighPassSkinSmoothing#11]

**Comment by YuAo** [comment]
See https://developer.apple.com/library/content/documentation/GraphicsImaging/Conceptual/CoreImaging/ci_performance/ci_performance.html

**Comment by notedit** [comment]
according to  https://stackoverflow.com/questions/28210847/converting-ciimage-to-cgimage-too-slow,   "This means that any filtering you may have applied (or better requested to apply) to your CIImage won't actually occur until you render the image"

```
[ciContext render:outimage toCVPixelBuffer:outPixelBuffer];  
```
this filter almost cost  100% cpu.

```
filter.inputAmount = @0.75;
filter.inputRadius = @(5+ 1);
```

anyway to optimize this

**Comment by notedit** [comment]
@YuAo  i am sure i have read that.  but still can not find better way to reduce cpu use.

**Comment by YuAo** [comment]
Can you profile your app using "Instruments" and post the bottleneck?

**Comment by notedit** [comment]
![image](https://user-images.githubusercontent.com/480864/29250110-3fc99222-806f-11e7-8413-77f6a3755c11.png)

first time use Instruments.  do i need provide more info?

**Comment by YuAo** [comment]
Here's a WWDC session on how to use time profiler in Instruments. https://developer.apple.com/videos/play/wwdc2016/418/

**Comment by notedit** [comment]
@YuAo   i create  an time profilter file   https://pan.baidu.com/s/1pKD7hLh

thanks

**Comment by YuAo** [comment]
All the debug symbols in your trace file are striped. Can't find any thing useful or anything related to the skin smoothing filter.

**Comment by notedit** [comment]
how i can give  you more info ?  

i just  test  CISepiaTone filter,  it cost  25% cpu.

**Comment by notedit** [comment]
if  i chage to 

```
 ciContext = [CIContext contextWithOptions:@{kCIContextWorkingColorSpace:[NSNull null]}];
```
80% cpu now,  almost half of before.

**Comment by YuAo** [comment]
Try a Metal based CIContext / set the 'inputSharpnessFactor' to 0 / reimplement this algorithm using Metal / use the GPUImage implementation.

**Comment by YuAo** [comment]
And don't create the filter everytime you use it.

**Comment by notedit** [comment]
yep, i have tried a lots of ways.  the cpu is still not very low.   i  will try GPUImage.
