### ISSUE TITLE
How to implement this beautify filter in live camera to beautify face

### ISSUE THREAD

**Issue by aaasifrz9** [YuAo/YUCIHighPassSkinSmoothing#12]
Hi @yien1108 , @YuAo ,

I tried GPUImage2, but there is no method to beautify face in the live camera. 
Can you please help how to implement this filter with the camera?

Thanks in advance.

**Comment by YuAo** [comment]
There's a Metal based implementation in MetalPetal (https://github.com/MetalPetal/MetalPetal). And a GPUImage based implementation in https://github.com/YuAo/YUGPUImageHighPassSkinSmoothing

**Comment by khush004** [comment]
@aaasifrz9 Have you implement this filter with the live camera?  I need Help.
