### ISSUE TITLE
Cannot use sRGB texture binding with format BGRA8 for sampler 0 in kernel 'filterKernel'.

### ISSUE THREAD

**Issue by gazind** [YuAo/YUCIHighPassSkinSmoothing#13]
Hi YuAo , your work is fantastic . ( Unfortunately im not smart enough to use it ).
 Failed to use  RGBToneCurve to filtering live iOS camera.  I would appreciate for your help . Thanks.

https://stackoverflow.com/questions/49933477/ios-yucirgbtonecurve-cannot-use-srgb-texture-binding-with-format-bgra8-for-sam

**Comment by YuAo** [comment]
Can you attach a sample project? Cannot reproduce here.

**Comment by YuAo** [comment]
Close due to inactivity.
