### ISSUE TITLE
let filter = CIFilter(name: "YUCIHighPassSkinSmoothing")! Crash

### ISSUE THREAD

**Issue by yashesh87** [YuAo/YUCIHighPassSkinSmoothing#14]
I am trying to access YUCIHighPassSkinSmoothing filter with CIFilter but I am not able to access it.

I am using the same code which you have provided in the sample like below:

let filter = CIFilter(name: "YUCIHighPassSkinSmoothing")!

Thanks!

**Comment by YuAo** [comment]
Your Xcode/Device/iOS version?

**Comment by yashesh87** [comment]
Xcode : 9.4
iOS : 11.4
Device : iPhoneX

**Comment by YuAo** [comment]
Any crash log，or error message？Have you tried to use the filter class directly? Like let filter = YUCIHighPassSkinSmoothing()
