### ISSUE TITLE
Apply filter on selected part of image

### ISSUE THREAD

**Issue by kk143g** [YuAo/YUCIHighPassSkinSmoothing#16]
How to apply that YUCIHighPassSkinSmoothing filter on selected/specific part of image, like pass a particular portion of image from image to apply filter on it, i have tried this
        let imageCenter = CIVector(x:0.55 * 100 , y:0.6 * 100)
        self.filter.setValue(imageCenter, forKey:"inputCenter")
But it says "this class is not key value coding-compliant for the key inputCenter"
I have applied above inputCenter in processImage() method of class DefaultRenderContextViewController.

**Comment by YuAo** [comment]
You can use a `CIBlendWithMask` filter(https://developer.apple.com/library/archive/documentation/GraphicsImaging/Reference/CoreImageFilterReference/index.html#//apple_ref/doc/filter/ci/CIBlendWithMask), with a static image or use `CIGaussianGradient` or `CIRadialGradient` to generate the mask image.
