### ISSUE TITLE
Removal of Red dots from Face

### ISSUE THREAD

**Issue by kk143g** [YuAo/YUCIHighPassSkinSmoothing#17]
I have tried different values of parameters but red dots are not removed from face. Is there any filter which can remove red dots from face. Acne is removed but red dots are still obvious. Suggest some filter or combination of filters. I have tried CIBloom filter with your algorithm, it just bloomed the face but still red dots are there.

**Comment by YuAo** [comment]
This is beyond what this library can do. What you are looking for is something like face deflect removing? Maybe take a look at opencv's `inpaint` function?
