### ISSUE TITLE
Pimples remover

### ISSUE THREAD

**Issue by kk143g** [YuAo/YUCIHighPassSkinSmoothing#18]
I have applied your High Paas filter to my desired images. Doing great job but one thing is missing, pimples are still there, Can you suggest some thing to remove these pimples?
Original image is this
![pic](https://user-images.githubusercontent.com/25244255/42454069-00613aa8-83a8-11e8-8cd5-be67fa164f35.png)

And after applying your filter
![img_6891](https://user-images.githubusercontent.com/25244255/42454231-608da24a-83a8-11e8-9f1e-9b6c65926dbe.PNG)
As you can see they are dimmed but not removed, Need urgently this work to be done, please suggest some thing,
Thanks

**Comment by YuAo** [comment]
You may need to use OpenCV. Try using edge detection then contour detection to find that deflect. Use something like inpaint to remove it.
