### ISSUE TITLE
c#?

### ISSUE THREAD

**Issue by GITMIKRO** [YuAo/YUCIHighPassSkinSmoothing#20]
Hi YuAo!  Very interesting work.  Do you have the capability to port this over to c# .NET or other Windows application code?  Is there any way to reach you by email or other method about contract work opportunities for you?

Thank you.

**Comment by YuAo** [comment]
It's not possible to port CoreImage related stuff to Windows. However you should be able to port this filter to Windows with the OpenGL implementation. See https://github.com/YuAo/YUGPUImageHighPassSkinSmoothing
