### ISSUE TITLE
principle of skinSmooth

### ISSUE THREAD

**Issue by shellin-star** [YuAo/YUCIHighPassSkinSmoothing#23]

**Comment by shellin-star** [comment]
hi AO,
Recently I am researching on skin smooth, and i'm lucky to see high contrast skin smooth algorithm on your github. There are some points i don't understand:
1. How the Curve Adjustment module  in the diagram preserve a fine level of detail;
2. Do you have a skin color segmentation to  keep the background detail constant?
3. In README， you mentioned that you have added two additional steps to improve the effect.，Can you give me more details? such as the formula for each step ^~^

**Comment by YuAo** [comment]
1. The curve adjustment is only applied to a selected set of pixels. The mask is produced by the `Mask Generating Routine`.
2. For this open source implementation, no.
3. The project is open source :)
