### ISSUE TITLE
inputToneCurveControlPoints invalid name in README

### ISSUE THREAD

**Issue by RomanFrom710** [YuAo/YUCIHighPassSkinSmoothing#24]
Hi, thanks for this great library!

I've noticed that there's a parameter called `inputControlPoints` in the README, but it's actually called `inputToneCurveControlPoints` in the [code](https://github.com/YuAo/YUCIHighPassSkinSmoothing/blob/4bb0aabf57fb34d2d24274213c70d3193d8aa1c5/Sources/YUCIHighPassSkinSmoothing.h), so trying to set `inputControlPoints` param leads to exception.

Also where I can read what exactly is "curve from the Curve Adjustment step" and what its values are responsible for? Thanks!

**Comment by YuAo** [comment]
https://helpx.adobe.com/photoshop/using/curves-adjustment.html

The values are the coordinates of control points.
