### ISSUE TITLE
Skin Smoothening making slow rendering on real camera.

### ISSUE THREAD

**Issue by shiwanithakur** [YuAo/YUCIHighPassSkinSmoothing#27]
It makes the performance of live camera slow.

**Comment by YuAo** [comment]
If you need better performance consider using https://github.com/MetalPetal/MetalPetal and https://github.com/MetalPetal/MetalPetal/blob/master/Frameworks/MetalPetal/Filters/MTIHighPassSkinSmoothingFilter.h
