### ISSUE TITLE
Love this project, but is it possible to implement this filter by GPUImage?

### ISSUE THREAD

**Issue by jinbo0122** [YuAo/YUCIHighPassSkinSmoothing#3]
When I use this filter to process live video buffer, cpu usage can goes up to 70% . Is it possible to reduce the cpu usage to under 15%, 25 frames per second. Besides, is GPUImage able to imitate the same effect with this great filter?

**Comment by YuAo** [comment]
I'll release the GPUImage version very soon. If you're dealing with real-time video, it is recommended to set the `inputSharpnessFactor` to `0`, see: https://github.com/YuAo/YUCIHighPassSkinSmoothing#input-parameters

**Comment by jinbo0122** [comment]
Great! Look forward to your GPUImage version!

**Comment by YuAo** [comment]
@jinbo0122 https://github.com/YuAo/YUGPUImageHighPassSkinSmoothing
