### ISSUE TITLE
hi, Could you please tell us the min/max values for the main settings such as the inputSharpnessFactor?

### ISSUE THREAD

**Issue by gaetano78** [YuAo/YUCIHighPassSkinSmoothing#6]

**Comment by YuAo** [comment]
The input parameters section contains the description for each parameter. https://github.com/YuAo/YUCIHighPassSkinSmoothing#input-parameters

inputAmount:  From 0.0 to 1.0

inputControlPoints: An array of control points. X, Y are from 0.0 to 1.0.

inputRadius: Radius in pixel of the high pass filter. From 0.0 to infinite.

inputSharpnessFactor: inputSharpnessFactor \* inputAmount is feeded to CISharpenLuminance's inputSharpness. See: https://developer.apple.com/library/tvos/documentation/GraphicsImaging/Reference/CoreImageFilterReference/index.html#//apple_ref/doc/filter/ci/CISharpenLuminance
