### ISSUE TITLE
Running on some other platform, i.e. Ubuntu?

### ISSUE THREAD

**Issue by msilic** [YuAo/YUCIHighPassSkinSmoothing#8]
Great library, is there any chance to run it on some other platform, in particular Ubuntu 14.04. TLS? Thank you in advance.

**Comment by YuAo** [comment]
You cannot run CoreImage on other platform, however you can use OpenGL.

You may want to look at the [GPUImage](https://github.com/BradLarson/GPUImage) version of this library https://github.com/YuAo/YUGPUImageHighPassSkinSmoothing
The GPUImage version uses OpenGL ES to achieve the same effect. 

In theory, you can port it to any platform that supports OpenGL.

In practise, you can start by porting this library to GPUImage2 https://github.com/BradLarson/GPUImage2 
This latest version of GPUImage is written entirely in Swift and can target Linux and future platforms that support Swift code.
